---
name: eliud_pkg_create
description: eliud_pkg_create is a package to provide create functionality to your
  eliud app (the ability to update the app through the gui). More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_create
version: 1.1.5+5
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.12.2
  collection: ^1.17.2
  eliud_core: ^1.1.5+7
  eliud_pkg_medium: ^1.1.5+5
  eliud_pkg_workflow: ^1.1.5+5
  eliud_pkg_text: ^1.1.5+6
  eliud_pkg_etc: ^1.1.5+8
  equatable: ^2.0.5
  file_picker: ^5.2.0+1
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  intl: ^0.18.1
  meta: ^1.9.1
  path_provider: ^2.1.1
  split_view: ^3.2.1
  flutter:
    sdk: flutter
dependency_overrides:   
  eliud_core: 
    path: ../eliud_core
  eliud_core_model: 
    path: ../eliud_core_model
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
  - packages/eliud_pkg_create/assets/annoyed.png
  - packages/eliud_pkg_create/assets/angry.png
  - packages/eliud_pkg_create/assets/embarassed.png
  - packages/eliud_pkg_create/assets/excited.png
  - packages/eliud_pkg_create/assets/frustrated.png
  - packages/eliud_pkg_create/assets/happy.png
  - packages/eliud_pkg_create/assets/lonely.png
  - packages/eliud_pkg_create/assets/loved.png
  - packages/eliud_pkg_create/assets/nervous.png
  - packages/eliud_pkg_create/assets/neutral.png
  - packages/eliud_pkg_create/assets/sad.png
  - packages/eliud_pkg_create/assets/scared.png
  - packages/eliud_pkg_create/assets/sick.png
  - packages/eliud_pkg_create/assets/stressed.png
  - packages/eliud_pkg_create/assets/surprised.png
  - packages/eliud_pkg_create/assets/tired.png
  - packages/eliud_pkg_create/assets/rodentia-icons_preferences-desktop-personal.png
platforms:
  android: null
  ios: null
  web: null
