name: eliud_pkg_create
description: Eliud package for app creator
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  eliud_core:
    path: ../eliud_core

  eliud_pkg_etc:
    path: ../eliud_pkg_etc

  eliud_pkg_text:
    path: ../eliud_pkg_text

  eliud_pkg_medium:
    path: ../eliud_pkg_medium

  eliud_pkg_follow:
    path: ../eliud_pkg_follow

  eliud_pkg_workflow:
    path: ../eliud_pkg_workflow

  eliud_pkg_chat:
    path: ../eliud_pkg_chat

#  eliud_pkg_feed:
#    path: ../eliud_pkg_feed

  eliud_pkg_pay:
    path: ../eliud_pkg_pay

  eliud_pkg_membership:
    path: ../eliud_pkg_membership

  eliud_pkg_shop:
    path: ../eliud_pkg_shop

dev_dependencies:
  build_runner: "1.11.5"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true

  assets:
    - packages/eliud_pkg_create/assets/new_app/legal/policies.pdf
    - packages/eliud_pkg_create/assets/annoyed.png
    - packages/eliud_pkg_create/assets/angry.png
    - packages/eliud_pkg_create/assets/embarassed.png
    - packages/eliud_pkg_create/assets/excited.png
    - packages/eliud_pkg_create/assets/frustrated.png
    - packages/eliud_pkg_create/assets/happy.png
    - packages/eliud_pkg_create/assets/lonely.png
    - packages/eliud_pkg_create/assets/loved.png
    - packages/eliud_pkg_create/assets/nervous.png
    - packages/eliud_pkg_create/assets/neutral.png
    - packages/eliud_pkg_create/assets/sad.png
    - packages/eliud_pkg_create/assets/scared.png
    - packages/eliud_pkg_create/assets/sick.png
    - packages/eliud_pkg_create/assets/stressed.png
    - packages/eliud_pkg_create/assets/surprised.png
    - packages/eliud_pkg_create/assets/tired.png
    - packages/eliud_pkg_create/assets/about.png
    - packages/eliud_pkg_create/assets/blocked.png
    - packages/eliud_pkg_create/assets/example_photo_1.jpg
    - packages/eliud_pkg_create/assets/example_photo_2.jpg
