---
name: eliud_pkg_create
description: eliud_pkg_create is a package to provide create functionality to your
  eliud app (the ability to update the app through the gui). More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_create
version: 1.3.0
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  eliud_core: ^1.3.0
  eliud_core_helpers: ^1.3.0
  eliud_core_main: ^1.3.0
  eliud_core_model: ^1.3.0
  eliud_pkg_create_model: ^1.3.0
  eliud_pkg_etc: ^1.3.0
  eliud_pkg_medium: ^1.3.0
  eliud_pkg_text: ^1.3.0
  eliud_pkg_workflow: ^1.3.0
  eliud_pkg_workflow_model: ^1.3.0
  bloc: ^8.1.4
  cloud_firestore: ^5.4.3
  collection: ^1.18.0
  equatable: ^2.0.5
  file_picker: ^8.1.2
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  meta: ^1.15.0
  http: ^1.2.2
  path_provider: ^2.1.4
  split_view: ^3.2.1
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.12
  eliud_generator: ^1.1.7
  lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
  - packages/eliud_pkg_create/assets/annoyed.png
  - packages/eliud_pkg_create/assets/angry.png
  - packages/eliud_pkg_create/assets/embarassed.png
  - packages/eliud_pkg_create/assets/excited.png
  - packages/eliud_pkg_create/assets/frustrated.png
  - packages/eliud_pkg_create/assets/happy.png
  - packages/eliud_pkg_create/assets/lonely.png
  - packages/eliud_pkg_create/assets/loved.png
  - packages/eliud_pkg_create/assets/nervous.png
  - packages/eliud_pkg_create/assets/neutral.png
  - packages/eliud_pkg_create/assets/sad.png
  - packages/eliud_pkg_create/assets/scared.png
  - packages/eliud_pkg_create/assets/sick.png
  - packages/eliud_pkg_create/assets/stressed.png
  - packages/eliud_pkg_create/assets/surprised.png
  - packages/eliud_pkg_create/assets/tired.png
  - packages/eliud_pkg_create/assets/rodentia-icons_preferences-desktop-personal.png
platforms:
  android: null
  ios: null
  web: null
