---
name: eliud_pkg_create
description: eliud_pkg_create is a package to provide create functionality to your
  eliud app (the ability to update the app through the gui). More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_create
version: 1.1.5+5
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  split_view: ^3.2.1                                                                                 # ANDROID IOS LINUX MACOS WEB WINDOWS

  eliud_core:                                                                                        # ANDROID IOS             WEB
    path: ../eliud_core
  eliud_core_main:                                                                                   # ANDROID IOS             WEB
    path: ../eliud_core_main
  eliud_core_helpers:                                                                                # ANDROID IOS             WEB
    path: ../eliud_core_helpers
  eliud_core_model:                                                                                  # ANDROID IOS             WEB
    path: ../eliud_core_model
  eliud_pkg_create_model:                                                                            # ANDROID IOS             WEB
    path: ../eliud_pkg_create_model
  eliud_pkg_medium:                                                                                  # ANDROID IOS             WEB
    path: ../eliud_pkg_medium
  eliud_pkg_workflow:                                                                                # ANDROID IOS             WEB
    path: ../eliud_pkg_workflow
  eliud_pkg_workflow_model:                                                                          # ANDROID IOS             WEB
    path: ../eliud_pkg_workflow_model
  eliud_pkg_text:                                                                                    # ANDROID IOS             WEB
    path: ../eliud_pkg_text
  eliud_pkg_etc:                                                                                     # ANDROID IOS             WEB
    path: ../eliud_pkg_etc

  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
  - packages/eliud_pkg_create/assets/annoyed.png
  - packages/eliud_pkg_create/assets/angry.png
  - packages/eliud_pkg_create/assets/embarassed.png
  - packages/eliud_pkg_create/assets/excited.png
  - packages/eliud_pkg_create/assets/frustrated.png
  - packages/eliud_pkg_create/assets/happy.png
  - packages/eliud_pkg_create/assets/lonely.png
  - packages/eliud_pkg_create/assets/loved.png
  - packages/eliud_pkg_create/assets/nervous.png
  - packages/eliud_pkg_create/assets/neutral.png
  - packages/eliud_pkg_create/assets/sad.png
  - packages/eliud_pkg_create/assets/scared.png
  - packages/eliud_pkg_create/assets/sick.png
  - packages/eliud_pkg_create/assets/stressed.png
  - packages/eliud_pkg_create/assets/surprised.png
  - packages/eliud_pkg_create/assets/tired.png
  - packages/eliud_pkg_create/assets/rodentia-icons_preferences-desktop-personal.png
platforms:
  android: null
  ios: null
  web: null
